spring.application.name=agriconnect-backend
server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

agriconnect.app.jwtSecret=${JWT_SECRET}
agriconnect.app.jwtExpirationMs=86400000
